# Generated by Django 2.1.1 on 2018-09-02 13:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trail.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('file', models.FileField(upload_to=trail.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['gpx'])], verbose_name='GPX file')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('uphill', models.FloatField(blank=True, null=True)),
                ('downhill', models.FloatField(blank=True, null=True)),
                ('min_altitude', models.FloatField(blank=True, null=True)),
                ('max_altitude', models.FloatField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('moving_time', models.FloatField(blank=True, null=True)),
                ('average_speed', models.FloatField(blank=True, null=True)),
                ('average_movement_speed', models.FloatField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date', 'name'],
            },
        ),
    ]
