# Generated by Django 2.1.1 on 2018-09-20 21:07

from django.db import migrations, models
import trail.models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='hero',
            field=models.FileField(null=True, upload_to=trail.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='trail',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
        migrations.AddField(
            model_name='trail',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Only you can see this trail', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
